let filter = 'all', entries = [];
const formatDate = iso => new Intl.DateTimeFormat('ar-SA', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(iso));
const escapeHtml = s => { const el = document.createElement('div'); el.textContent = s; return el.innerHTML; };
async function loadEntries() { const response = await fetch('/.netlify/functions/answers'); entries = response.ok ? await response.json() : []; render(); }
function render() { const correct = entries.filter(x => x.correct).length, shown = entries.filter(x => filter === 'all' || (filter === 'correct' ? x.correct : !x.correct)); document.getElementById('totalCount').textContent = entries.length; document.getElementById('correctCount').textContent = correct; document.getElementById('wrongCount').textContent = entries.length - correct; document.getElementById('answerCaption').textContent = `${shown.length} مشاركة معروضة`; document.getElementById('answersBody').innerHTML = shown.map(x => `<tr><td>${escapeHtml(x.name)}</td><td>${escapeHtml(x.department)}</td><td>${escapeHtml(x.answer)}</td><td><span class="badge ${x.correct ? 'correct' : 'wrong'}">${x.correct ? 'صحيحة' : 'غير صحيحة'}</span></td><td>${formatDate(x.submittedAt)}</td></tr>`).join(''); document.getElementById('emptyState').hidden = shown.length > 0; }
document.querySelectorAll('.filter').forEach(btn => btn.addEventListener('click', () => { filter = btn.dataset.filter; document.querySelectorAll('.filter').forEach(x => x.classList.toggle('active', x === btn)); render(); }));
document.getElementById('drawWinner').addEventListener('click', () => { const pool = entries.filter(x => x.correct), holder = document.getElementById('winner'); if (!pool.length) { holder.textContent = 'لا توجد إجابات صحيحة للسحب منها.'; return; } const winner = pool[Math.floor(Math.random() * pool.length)]; holder.innerHTML = `🎉 الفائز: <strong>${escapeHtml(winner.name)}</strong><span>${escapeHtml(winner.department)}</span>`; });
document.getElementById('resetWinner').addEventListener('click', () => document.getElementById('winner').textContent = 'لم يتم إجراء سحب بعد');
document.getElementById('clearAll').addEventListener('click', async () => { if (confirm('هل تريد حذف جميع الإجابات نهائيًا؟')) { await fetch('/.netlify/functions/answers', { method: 'DELETE' }); document.getElementById('winner').textContent = 'لم يتم إجراء سحب بعد'; loadEntries(); } });
loadEntries();
